### ISSUE TITLE
Add option to pass strings from a file instead of command line

### ISSUE THREAD

**Issue by kud1ing** [pemistahl/grex#1]
Multiple and more complex input strings would probably be easier to pass from a file.

**Comment by pemistahl** [comment]
@kud1ing I agree. This is already on my todo list for version 0.2.0. 

Thank you for trying my tool and for opening this issue.

**Comment by pemistahl** [comment]
This feature has been implemented in version 0.2.0.

**Comment by kud1ing** [comment]
Nice, thank you.
