### ISSUE TITLE
Add feature for specifying lower bound for repetition conversion

### ISSUE THREAD

**Issue by templarundead** [pemistahl/grex#10]
Optimizing repetitions with less than four characters doesn't make sense – we get larger regular expressions in the output

Bad optimization
input: zoom - four characters
output: zo{2}m - six characters

Bad optimization
input: zooom - five characters
output: zo{3}m - six characters

Not bad
input: zoooom - six characters
output: zo{4}m - six characters

Good optimization 
input: zooooom - seven characters
output: zo{5}m - six characters

**Comment by pemistahl** [comment]
Hi @templarundead, thanks for your input. I think it's a matter of taste in the end whether you want the original or the quantifier notation for repetitions less than four characters.

What would you say if I introduced an additional command-line flag such as `--min` with a default value of 4? Then the repetition conversion would only happen for a minimum of four repeated characters. If the user wanted to change the value, they would be able to do so.

Would that be to your liking? If so, I will plan this feature for the next release.

**Comment by templarundead** [comment]
Yes as an additional option it would be useful

**Comment by pemistahl** [comment]
Now this is done. Closed.
