### ISSUE TITLE
Input starting with a hyphen results in an error

### ISSUE THREAD

**Issue by ozgurgunes** [pemistahl/grex#12]
As title says:

```
% grex "- Input starting with a hyphen" 
error: Found argument '- ' which wasn't expected, or isn't valid in this context

USAGE:
    grex [FLAGS] <INPUT>... --file <FILE>

For more information try --help
```

**Comment by pemistahl** [comment]
Hi @ozgurgunes, thank you for letting me know about this issue. 

I've just found out that, strictly speaking, this is not a bug in _grex_ but a configuration issue in the underlying command-line argument parser [_clap_](https://github.com/clap-rs/clap). It disallows leading hyphens in argument values by default which leads to your error. [This setting can be changed](https://docs.rs/clap/latest/clap/enum.AppSettings.html#variant.AllowLeadingHyphen), so it should be easy to solve this problem. I will fix it for the next release.
