### ISSUE TITLE
Overly complex regex with input containing several common parts

### ISSUE THREAD

**Issue by waldyrious** [pemistahl/grex#20]
While building a regex for the [various possible formats](https://github.com/creativecommons/cc.license/blob/a134299fdb0e882b84a2c181afc5588e13ae32df/cc/license/formatters/classes.py#L328-L361) of Creative Commons' Public Domain Mark (to assist in https://github.com/spdx/license-list-XML/issues/988), I noticed that grex produces a more complex regex than what the input requires.

Here's what I provided:

```sh
grex \
  "This work is free of known copyright restrictions." \
  "This work (WWW) is free of known copyright restrictions." \
  "This work (by AAA) is free of known copyright restrictions." \
  "This work, identified by CCC, is free of known copyright restrictions." \
  "This work (WWW, by AAA) is free of known copyright restrictions." \
  "This work (WWW), identified by CCC, is free of known copyright restrictions." \
  "This work (WWW, by AAA), identified by CCC, is free of known copyright restrictions." \
  "This work (by AAA), identified by CCC, is free of known copyright restrictions."
```

The result was (after manually [making groups non-capturing](https://github.com/pemistahl/grex/issues/15)):

```regex
^This work(?:(?: \((?:(?:WWW, b|b)y AAA|WWW)\),|,) identified by CCC, |(?: \((?:(?:WWW, b|b)y AAA|WWW)\) | ))is free of known copyright restrictions\.$
```

Visualized as a [Debuggex](https://www.debuggex.com/) diagram:

![Screenshot 2020-03-10 at 14 20 39](https://user-images.githubusercontent.com/478237/76321744-5d8aee00-62da-11ea-918e-1db494906b03.png)

A regex produced by hand to match the same input shows that this could be simplified:

```regex
^This work(?: \((?:WWW(?:, by AAA)?|by AAA)\))?(?:, identified by CCC,)? is free of known copyright restrictions\.$
```

Debuggex diagram:

![Screenshot 2020-03-10 at 12 22 50](https://user-images.githubusercontent.com/478237/76311942-ea797b80-62c9-11ea-9094-972d4fe63481.png)

**Comment by pemistahl** [comment]
Thanks for letting me know about this @waldyrious. I'm aware of the fact that the produced regexes are not always the most optimal ones. I'll keep on improving regex generation with each new release. As there is no concrete task that can be derived from your findings, I close this issue now. But I will keep it as a reference and come back to it later.

**Comment by waldyrious** [comment]
Thanks for the quick response. I understand that this issue does not suggest a specific solution, but I does identify a specific problem. Couldn't it be used to track this specific case as one of the regex generation improvements? It would then be closed once grex is able to produce the expected output for this specific case.

**Comment by pemistahl** [comment]
> I understand that this issue does not suggest a specific solution, but it does identify a specific problem.

No, it does not identify a specific problem. It simply shows, for a completely arbitrary set of test cases, that the resulting regex is not the shortest one possible. If you were able to find reproducible examples that always produce the same kind of obsolete regex repetition, and if you were able to name this kind of obsolete regex repetition, then you would identify a specific problem. This is not the case there, so I have closed the issue.

**Comment by c2ray** [comment]
Could it be possible to provide an option, for example `-k 'is free of known copyright restrictions'` to keep this sentense not being parsed to a regex.
