### ISSUE TITLE
Please add support for arm arch

### ISSUE THREAD

**Issue by owenstake** [pemistahl/grex#208]
Please add support for arm arch

**Comment by pemistahl** [comment]
Do you mean ARM for MacOS? I provide a binary for that already on the releases page. You also find a link to it at the top of the readme file.

**Comment by owenstake** [comment]
> Do you mean ARM for MacOS? I provide a binary for that already on the releases page. You also find a link to it at the top of the readme file.

linux-aarch64

**Comment by pemistahl** [comment]
ARM binaries are now provided for every platform in version 1.4.5.
