### ISSUE TITLE
Any idea how to better do classes?

### ISSUE THREAD

**Issue by sburkett** [pemistahl/grex#28]
This sounded like just the tool I needed to get the job done, and it may be, but perhaps I'm just not using it correctly.

The use-case here is that I have a file with almost 2 million filenames in it. Over the years, there have been several different file naming conventions, and I'm trying to determine how many of each there are (the easy way, of course).

At any rate, given something like this: `_001715_1406309_.pdf` I get:

```
$ grex _001715_1406309_.pdf
^_001715_1406309_\.pdf$
```

```
$ grex -r _001715_1406309_.pdf
^_0{2}1715_1406309_\.pdf$
```

I was hoping I could generate regex patterns which are more inclusive, using classes, such as:

```
^_[0-9]*_[0-9]_\.pdf$
```

The `-r` option looked promising, but it just looks for characters which repeat exactly, not characters which would match some obvious character classes such as `[:alpha:]`, `[:digit:]`, etc.

Ideally it would be configurable so that I could get:

```
^_[0-9]*_[0-9]_\.pdf$
```

instead of something like these:

```
^_[0-9]*_[0-9]_\.[a-z]*$
^_[0-9]{6}_[0-9]{7}_\.[a-z]{3}$
```

Dunno, just riffing out loud. Interesting tool, though :)

Hope that makes sense. Any ideas or suggestions for using `grex` or anything else to get the job done? Thanks!

**Comment by pemistahl** [comment]
Hello Scott, thank you for trying my tool and for your question. :)

Well, I think the most useful setting for your use case is currently this:

```
$ grex -dr _001715_1406309_.pdf
^_\d{6}_\d{7}_\.pdf$
```

Your ideas to support more character classes such as `[:alpha:]` are worth to consider. Actually, there are tons of possible extensions for a tool like this. I just don't have the time for further development at the moment. But this will change some time in the future.

If you are not afraid of digging into the code yourself, feel free to send me a pull request. But the code is not easy, I must admit.

Does that answer your question for now? If so, I will close this issue.
