### ISSUE TITLE
What is the name of the font used in the logo?

### ISSUE THREAD

**Issue by cata0309** [pemistahl/grex#29]

**Comment by pemistahl** [comment]
This remains my little secret. Don't simply copy, be creative! :)

**Comment by cata0309** [comment]
I just want to use it in one of my text-editors! I don't understand! What did I say wrong?

**Comment by cata0309** [comment]
@pemistahl

**Comment by cata0309** [comment]
I find it without your help! The name for anyone who is looking is Kautiva, can be found at https://www.myfonts.com/fonts/sudtipos/kautiva
@pemistahl I hope you are happy with your behavior!
