### ISSUE TITLE
Make anchors `^` and `$` optional

### ISSUE THREAD

**Issue by mathiasbynens** [pemistahl/grex#30]
One of the use cases for grex (IMHO) is to use its generated patterns as part of a larger pattern. In this case, the `^` and `$` anchors in the output are not desired. Have you considered making this optional?

**Comment by pemistahl** [comment]
Hi Mathias, thanks for your request. 

I have not thought about making anchors optional yet but this could actually be useful sometimes. Adding the anchors should remain the default though. I will think about whether to include this as a new feature in the next release.

**Comment by ildar-shaimordanov** [comment]
I vote too for making these anchors optional. They could be placed in the outcome with help of additional CLI options. For example:
* `-B`, `--match-beginning` for `^`
* `-E`, `--match-end` for `$`
* also `-X`, `--match-line` for both `^` and `$` (as a shorthand for `-B -E`)
