### ISSUE TITLE
Problem install win7  scoop install grex

### ISSUE THREAD

**Issue by AlexandrDragunkin** [pemistahl/grex#33]
Perhaps this is not a GREX error. I decided to inform, since I had to transfer the file to ... \scoop\shims \

![image](https://user-images.githubusercontent.com/18010682/112845080-21752780-90ad-11eb-89b7-c1a06b560a81.png)

**Comment by pemistahl** [comment]
I'm sorry @AlexandrDragunkin, that was actually my fault. There is a bug in the GitHub release workflow which I will fix later. I've manually fixed the zip distribution file for Windows now, so please try again installing it using scoop.

Please report if it works. I will then close this issue. Thank you.

**Comment by AlexandrDragunkin** [comment]
Boom!
![image](https://user-images.githubusercontent.com/18010682/112850748-f7266880-90b2-11eb-83ae-b7a0e7373340.png)

**Comment by pemistahl** [comment]
Does Scoop save the hash value of the previous zip file in some kind of cache? If so, can you perhaps delete this cache somehow? I think it should work then. In case of doubt, please ask the Scoop guys. I don't have a Windows PC for testing and  no other idea at the moment.

**Comment by AlexandrDragunkin** [comment]
Everything turned out great!
We need to update the scoop.
Maybe a screenshot will help someone?!
![image](https://user-images.githubusercontent.com/18010682/112861469-7de04300-90bd-11eb-93ba-5db16021edaa.png)

**Comment by pemistahl** [comment]
Great! :) I'm happy that you could solve the problem. Sorry again for the inconvenience. Windows users will not have a problem anymore from now on.
