### ISSUE TITLE
Grex hash for v1.2.0 release fails to verify in scoop

### ISSUE THREAD

**Issue by piaseckim** [pemistahl/grex#34]
Simple as that:
```
λ scoop install grex
Installing 'grex' (1.2.0) [64bit]
grex-v1.2.0-x86_64-pc-windows-msvc.zip (792,6 KB) [==========================================================================================================================] 100%
Checking hash of grex-v1.2.0-x86_64-pc-windows-msvc.zip ... ERROR Hash check failed!
App:         main/grex
URL:         https://github.com/pemistahl/grex/releases/download/v1.2.0/grex-v1.2.0-x86_64-pc-windows-msvc.zip
First bytes: 50 4B 03 04 14 00 00 00
Expected:    d075efdbccb01c8b093b6c5120d064cc5ead534dec483c1a3d43cc4543d940ea
Actual:      da9c50a4e19cbf7b1c4a001a9252c1a097b8eebbb9ec0bbf3f88bc79030e7d73
```
Creating issue as this may be an overlooked thing.
Another option is that I'm facing MIM attack which would be worse case scenario ;)

**Comment by pemistahl** [comment]
This looks like the same problem as in #33. Can you please run `scoop update` first and then try to install it again? The other user was successful with that approach. Thank you.

**Comment by TrikkStar** [comment]
I'm getting the same problem, and doing an uninsall-reinstall doesn't seem to help.

> C:\WINDOWS\system32>scoop install grex
Installing 'grex' (1.2.0) [64bit]
grex-v1.2.0-x86_64-pc-windows-msvc.zip (792.6 KB) [===========================================================] 100%
Checking hash of grex-v1.2.0-x86_64-pc-windows-msvc.zip ... ERROR Hash check failed!
App:         main/grex
URL:         https://github.com/pemistahl/grex/releases/download/v1.2.0/grex-v1.2.0-x86_64-pc-windows-msvc.zip
First bytes: 50 4B 03 04 14 00 00 00
Expected:    d075efdbccb01c8b093b6c5120d064cc5ead534dec483c1a3d43cc4543d940ea
Actual:      da9c50a4e19cbf7b1c4a001a9252c1a097b8eebbb9ec0bbf3f88bc79030e7d73
>
>Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Main/issues/new?title=grex%401.2.0%3a+hash+check+failed

**Comment by pemistahl** [comment]
As it turns out, somebody has already [opened a pull request](https://github.com/ScoopInstaller/Main/pull/2013) in the Scoop repository. The new hash value of my manually fixed Windows distribution zip file obviously needs to be updated there.

I was not aware of this. I'm sorry for any inconvenience caused. I'm sure that pull request will be merged shortly. Afterwards, you will be able to install grex without any problems.

**Comment by pemistahl** [comment]
The Scoop pull request has just been merged. Please report whether it works now. I will then close this issue. Thanks.

**Comment by TrikkStar** [comment]
Can confirm that the install is working now.
