### ISSUE TITLE
Inserting a character breaks repetition detection (sometimes)

### ISSUE THREAD

**Issue by loveencounterflow** [pemistahl/grex#36]
I have been looking for a way to find repeated substrings. I think I can parse grex results to find repetitions, and given that my strings are rather short, I could then compare group contents to find non-contiguous repetitions.

I did some quick tests and I may have chanced upon a problem:

* `grex -dsr -c 'heeelooo world lalala lalala foo foo xalxalxal xalxalxal'`

  gives `^he{3}lo{3}\sworld(?:\s(?:la){3}){2}(?:\sfo{2}){2}(?:\s(?:xal){3}){2}$`
  
* `grex -dsr -c 'heeelooo world lalala lalala foo foo xalxalxal i xalxalxal'`

  gives `^he{3}lo{3}\sworld\s(?:(?:la){3}\s){2}(?:fo{2}\s){2}(?:xal){3}\si\s(?:xal){3}$`
  
* `grex -dsr -c 'heeelooo world lalala k lalala foo foo xalxalxal i xalxalxal'`

  gives `^he{3}lo{3}\sworld\slalala\sk\slalala\s(?:fo{2}\s){2}(?:xal){3}\si\s(?:xal){3}$`
  
In the last probe, neither of the two `lalala` was detected as repetitious when a `k` was inserted, although `xalxalxal` was treated as expected. Any thoughts?

**Comment by loveencounterflow** [comment]
more minimally:

```sh
grex -dsr -c 'xalxalxal i xalxalxal'     
^(?:xal){3}\si\s(?:xal){3}$
grex -dsr -c 'xalxalxal xalxalxal'       
^xalxalxal\sxalxalxal$
grex -dsr -c 'foo xalxalxal xalxalxal'                          
^fo{2}(?:\s(?:xal){3}){2}$
```

**Comment by pemistahl** [comment]
Thank you @loveencounterflow for the report. I will evaluate this problem some time in the future but I cannot tell you when exactly. I will let you know.

**Comment by pemistahl** [comment]
I've finally fixed this issue @loveencounterflow. Perhaps you want to try it again yourself. I think it's safe now.
