### ISSUE TITLE
Document how to use grex in shell filters

### ISSUE THREAD

**Issue by GregLawson** [pemistahl/grex#38]
Added documentation suggestion:
It is quite handy to filter inputs to grex through tools such as head, tail, cat, and grep for a variety of use cases:
1) to produce simpler regexps for sanity checking grex outputs. 
2) generating separate simpler regexp for subsets of your data (e.g. headers versus data).
3) generate separate simpler regexp for errors or anomalies using grep's -v, --invert-match options
On Linux reading from standard input can be achieved with the nonstandard option --file /dev/stdin

**Comment by pemistahl** [comment]
Thank you @GregLawson for your suggestion. However, I won't start documenting other tools here. I think people are clever enough to come up with various ideas of combining grex with other command-line tools to make it even more useful.
