### ISSUE TITLE
JavaScript/TypeScript bindings to the browser and nodejs

### ISSUE THREAD

**Issue by KrzysztofZawisla** [pemistahl/grex#40]
Hi, inspirited by that awesome library I decided to create bindings to it.

https://github.com/KrzysztofZawisla/grex.js

That lib exposes rust `RegExpBuilder::from` function to browser and nodejs. There are 2 options of import. Version with the native module or wasm module. Would be awesome if you would add a reference to the JavaScript version of the library in README.

Greetings
Krzysztof Zawisła

**Comment by pemistahl** [comment]
Hi Krzysztof, thanks for the great work. :) I will gladly mention it in my README.

**Comment by pemistahl** [comment]
Done. :)
