### ISSUE TITLE
Couldn't compile ndarray

### ISSUE THREAD

**Issue by Mayt38** [pemistahl/grex#41]
Hey I'm on Debian bullseye and `cargo install grex` won't succeed : 
```
[lots of errors]
error: aborting due to 204 previous errors

For more information about this error, try `rustc --explain E0277`.
error: could not compile `ndarray`.
```

ndarray version = 0.15.1
cargo version = 1.47

has someone experienced the same issue ?

**Comment by pemistahl** [comment]
Hi @Mayt38, this could be the same problem as reported in #37. Please update your Rust toolchain to the latest version using `rustup update stable` and try the compilation again. Does that help?

**Comment by pemistahl** [comment]
As I haven't heard anything from you in the meantime, I'm closing this issue now. If it still exists, then please re-open it again. Thank you.

**Comment by Mayt38** [comment]
I'm using debian where rustup isn't the pakaged, and rust version in apt is 1.46. It's is indeed far from the last stable version. I tried setting up the toolchain with rustup, and everything works fine!
Thanks
