### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by tmanito** [pemistahl/grex#46]
facing a weird issue while installing grex

```
$ sudo cargo install grex
    Updating crates.io index
error: process didn't exit successfully: `rustc -vV` (exit status: 127)
--- stderr
rustc: relocation error: /lib64/librustc_driver-eaa0856b54809337.so: symbol _ZNK4llvm18DiagnosticLocation15getAbsolutePathEv, version LLVM_11 not defined in file libLLVM-11.so with link time reference
```

**Comment by pemistahl** [comment]
This has nothing to do with grex. You are on Linux, right? Your Rust installation is probably broken. Please reinstall the latest Rust version and try again. 

The simpler way is to download one of the grex binaries instead of compiling it from source.
