### ISSUE TITLE
Character escaping gets confused when the input string contains a unicode-escape symbol itself.

### ISSUE THREAD

**Issue by christophebiocca** [pemistahl/grex#5]
Examples found by the code in #4:

- `"\u{70f}["`
- `"\u{110cd}("`

These are all passed through as-is but that's not valid.

~~Worth noting that `"\u{110cd}"` and similar get passed through as well, which is a syntactically valid regex but will not match the input string.~~ Nope, that was just me misunderstanding how unicode escapes work.

- `\u{600}*` also is passed through as is, which is syntactically valid but will not match itself.

**Comment by pemistahl** [comment]
Thanks, @christophebiocca. I will deal with these bugs when I write my own property tests.

**Comment by christophebiocca** [comment]
FWIW from looking over the code trying to pin down/fix the problem, it seems the root cause is that `Grapheme`s sometimes contain escaped strings, and sometimes don't, which makes doing the right thing difficult.

A design that would cut down on these kinds of bugs would be to do no escaping until the very final step. A dedicated trait ("ToRegexString") with a single method that takes all of the configuration parameters (`escape` and `with-surrogates`) at that time seems most likely to work.

**Comment by pemistahl** [comment]
This has been fixed in version 0.3.1. Closed.
