### ISSUE TITLE
Feature Request: Allow to pipe text into grex

### ISSUE THREAD

**Issue by jgarte** [pemistahl/grex#59]
I'd like to be able to pipe text into grex. 

For example

`echo "hello      world    543" | grex -g`

Would it be possible to support this feature?

My use case would be that I could select the text in visual mode and pipe it through grex to get back a regex in place that I can further edit in the buffer.

I use [vis](https://github.com/martanne/vis/wiki/Differences-from-Kakoune) as my main editor which has `<`, `>`, `|`, and `!` operators in command mode.

**Comment by jgarte** [comment]
Ah, TIL `echo hello | xargs grex`.

Would it be able to implement piping above as "first class" so that xargs is not required? Or, should I just make a script with xargs to avoid adding more code to grex?

**Comment by pemistahl** [comment]
Hi @jgarte, the feature you want is already supported. Please read section 5 in the README.

```
~ % echo "hello world 543" | grex -
^hello world 543$
```
