### ISSUE TITLE
Add optional CLI feature if using grex as a library

### ISSUE THREAD

**Issue by jqnatividad** [pemistahl/grex#61]
Hi @pemistahl, first off, thanks for this wonderful library!  

But would it be possible to have an optional CLI feature in cargo.toml?

In that way, if I'm using grex as a library, I don't need to get dependencies like structopt  included in my project.

**Comment by jqnatividad** [comment]
Hi @pemistahl , just wondering if you have an ETA for the 1.3.1 release...

**Comment by pemistahl** [comment]
No @jqnatividad, I don't have an ETA at the moment. I've been busy doing other stuff, recently. I will continue to work on *grex* soon.

**Comment by jqnatividad** [comment]
Thanks @pemistahl for the update! Looking forward to the soonish release! 😉

**Comment by jqnatividad** [comment]
Awesome @pemistahl ! Thanks for merging #62 and #68!

Hope to see the latest release on crates.io soon!
